### ISSUE TITLE
스플래시 만들면서 AndroidManifest.xml에 경고하나 있었음

### ISSUE THREAD

**Issue by glass1222** [Onewoo/CoronaMaskMap#2]
커밋하려고 했을때 SDK 구버전이라 뜨는 경고인지 하나 있었음.
자세히는 뭐가 문제인지 모르겠음;;

근데 앱 구동에는 문제없지만 혹시나해서 남겨놓음.

혹시나 나중에 문제되면 확인해야 할 수 있으니까

**Comment by Onewoo** [comment]
수정 완료
